### ISSUE TITLE
The Workflow import in WebIDE does not work

### ISSUE THREAD

**Issue by slottmandeloitte** [SAP-samples/s4hana-ext-situation-handling#1]
I am following the steps to import the Workflow project in the WebIDE.  The project is imported, but there are no tasks or steps in the graphical editor.  When trying to deploy the workflow to SCP I get an error.

**Comment by meakgoz2** [comment]
Hi,

Thanks for showing interest in our sample. 

To be able to help you, I would need more detail on the error. Following would help;

1. What is the console output (you can open the console in Web IDE by clicking the console button on the bottom-right of the IDE)? 
2. Screenshot of the workspace after you import the project.

From the description you have provided I have some guess what might have gone wrong. So I would like you to check the following;
1. Are you following the steps in the [guide](https://help.sap.com/viewer/160539efd20c4dcea8a1b945ae32500b/SHIP/en-US/cf3fd36365384f99b0ee8ae751a0f21e.html). Especially the _Note_ in the Prerequisites section:
>Please extract the production zip file first, and you'll find the situation-handling-workflow.zip file that you'll work with.

Downloaded zip file has another zip file inside, and the inner one is the file should be imported.
So when you import a project, import dialog will look like this:
![image](https://user-images.githubusercontent.com/31985335/68107077-e7b5e680-fee3-11e9-8254-45bf1be1fd35.png)

And afterwards your workspace should look like this (❗️ folder structure is important, please check the folder structure):
![image](https://user-images.githubusercontent.com/31985335/68107129-103de080-fee4-11e9-86a5-329a7cd899d8.png)

2. Have you enabled the Workflow Editor extension on your Web IDE Full Stack, and click the save button (it should refresh the browser after clicking the save button)? 
![image](https://user-images.githubusercontent.com/31985335/68107167-3bc0cb00-fee4-11e9-83b9-7ba0ca4e0270.png)

**Comment by meakgoz2** [comment]
Closing the issue due to inactivity.
Hope the explanation helped to solve the problem.

Please feel free to re-open the issue if the problem persist, or create a new issue if you face any other problem.
