### ISSUE TITLE
Business Rules Editor Project: Import project or even tried create project  throws me error. see attached.

### ISSUE THREAD

**Issue by sampathr100** [SAP-samples/s4hana-ext-situation-handling#2]
with SAP Cloud Platform Business Rules Project :

I am trying to upload situation-handling-rules.zip (the zip inside the main zip) , by choosing upload zip from file system option
 i get error message "some unknown error has occured. please contact technical support". 

and i see this in Logging section of Business Rules service:

2020-02-08T22:22:04,722+0000#733876938#ERROR#Socket connection timed out for host https://bpmrulesrepositorybpm-i851071trial.hanatrial.ondemand.com/rules-service. Reason: Read timed out (local port 49632 to address 10.117.12.116 (vsa7282767.nwtrial.od.sap.biz), remote port 443 to address 155.56.219.22)

tenant: i851071trial

please see my attache
<img width="1649" alt="Screen Shot 2020-02-08 at 5 23 05 PM" src="https://user-images.githubusercontent.com/16802759/74092901-b297d200-4a98-11ea-8ced-202b025ae334.png">
<img width="1653" alt="Screen Shot 2020-02-08 at 5 06 58 PM" src="https://user-images.githubusercontent.com/16802759/74092902-b6c3ef80-4a98-11ea-830d-883cde219b67.png">
<img width="1660" alt="Screen Shot 2020-02-08 at 4 55 32 PM" src="https://user-images.githubusercontent.com/16802759/74092903-b9264980-4a98-11ea-8bb8-6b490b734cdc.png">
![Uploading Screen Shot 2020-02-08 at 4.55.10 PM.png…]()

d screenshot

**Comment by meakgoz2** [comment]
The problem was in the subaccount.
Importing any rules as well as creating a new rules project was not possible.
It was resolved after disabling and re-enabling the Business Rule service.

Please feel free to create a new issue if you face any other problem.
